version: "2"
run:
  timeout: 10m
  allow-parallel-runners: true

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kube-logging/logging-operator)
    goimports:
      local-prefixes:
        - github.com/kube-logging/logging-operator
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false

linters:
  settings:
    misspell:
      locale: US
    revive:
      confidence: 0.9
    gocyclo:
      min-complexity: 15
  enable:
    - bodyclose
    - errcheck
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace
