name: E2E tests

on:
  push:
    branches:
      - master
      - "release-[0-9]+.[0-9]+*"
  pull_request:

env:
  KUBECTL_VERSION: 'v1.32.0'

jobs:
  build:
    name: Build ${{ matrix.image }} image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: fluentd
            context: images/fluentd
            tags: fluentd-full:local
            target: full
            output: fluentd-full.tar
          - image: controller
            context: .
            tags: controller:local
            target: e2e-test
            build_args: GO_BUILD_FLAGS=-cover -covermode=atomic
            output: controller.tar
          - image: config-reloader
            context: images/config-reloader
            tags: config-reloader:local
            output: config-reloader.tar
          - image: syslog-ng-reloader
            context: images/syslog-ng-reloader
            tags: syslog-ng-reloader:local
            output: syslog-ng-reloader.tar
          - image: fluentd-drain-watch
            context: images/fluentd-drain-watch
            tags: fluentd-drain-watch:local
            output: fluentd-drain-watch.tar

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build and export ${{ matrix.image }}-image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ${{ matrix.context }}
          tags: ${{ matrix.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ matrix.target }}
          build-args: ${{ matrix.build_args }}
          outputs: type=docker,dest=/tmp/${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: e2e-${{ matrix.image }}
          path: /tmp/${{ matrix.output }}

  go:
    name: Go end2end tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
#      matrix:
#        SHARD: [0]
#        SHARDS: [1]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Download artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          pattern: e2e-*
          path: /tmp
          merge-multiple: true

      - name: Load image
        run: |
          docker load --input /tmp/fluentd-full.tar
          docker load --input /tmp/config-reloader.tar
          docker load --input /tmp/syslog-ng-reloader.tar
          docker load --input /tmp/fluentd-drain-watch.tar
          docker load --input /tmp/controller.tar
          docker image ls -a

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: '.go-version'

      - name: Set up kubectl
        uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8 # v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Run e2e tests
        run: make test-e2e-ci
#        env:
#          SHARD: ${{ matrix.SHARD }}
#          SHARDS: ${{ matrix.SHARDS }}

      - name: Run coverage report
        uses: vladopajic/go-test-coverage@992aa9921a42c39d1fe0015d32593f0820589586 # v2.13.0
        with:
          profile: ./build/_test_coverage/coverage_e2e.out
          source-dir: ./

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: go-e2e-test-cluster-logs
          path: build/_test
          retention-days: 5

  chart:
    name: Shell script tests with chart install
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        kube: ["1.30", "1.31", "1.32"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Download artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          pattern: e2e-*
          path: /tmp
          merge-multiple: true

      - name: Load image
        run: |
          docker load --input /tmp/fluentd-full.tar
          docker load --input /tmp/config-reloader.tar
          docker load --input /tmp/syslog-ng-reloader.tar
          docker load --input /tmp/fluentd-drain-watch.tar
          docker load --input /tmp/controller.tar
          docker image ls -a

      - name: Set up kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # See https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
      - name: Determine KinD node image version
        id: node_image
        run: |
          case ${{ matrix.kube }} in
            1.30)
              NODE_IMAGE=kindest/node:v1.30.0@sha256:2af5d1b382926abcd6336312d652cd045b7cc47475844a608669c71b1fefcfbc ;;
            1.31)
              NODE_IMAGE=kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865 ;;
            1.32)
              NODE_IMAGE=kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
            esac

            echo "image=$NODE_IMAGE" >> $GITHUB_OUTPUT

      - name: Make setup
        run: make kind-cluster stern
        env:
          KIND_IMAGE: ${{ steps.node_image.outputs.image }}

      - name: Test
        run: hack/test.sh

      - name: Print last 10k kubernetes logs from default and logging namespaces
        if: always()
        run: |
          mkdir -p build/_test
          bin/stern -n default,logging ".*" --tail 100000 --no-follow > build/_test/cluster.logs

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: script-e2e-test-cluster-logs-${{ matrix.kube }}
          path: build/_test
          retention-days: 5
