name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      version: ${{ github.ref_name }}
      publish: true
      release: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

  dependency-images:
    name: Dependency images
    uses: ./.github/workflows/dependency-images.yaml
    with:
      fluentd-image-types: "base,filters,full"
      publish: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
